EcommerceWEBApplication/Controllers/Services/ServicesController.cs
using BAL.Factory;
using BAL.Interfaces;
using Components.RequestObjects;
using Components.ResponseObjects;
using EcommerceWEBApplication.Filters; 
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using EcommerceWEBApplication.Models.Entity;
using Components;

namespace EcommerceWEBApplication.Controllers.Services
{
    public class ServicesController : Controller
    {
        // GET: Services
        private readonly ICategoryManagementService _categoryManagementService;
        private readonly IYPAdmanagementService _ypAdmgmtService;
        MyQShopsEntities context = new MyQShopsEntities();
        public ServicesController()
        {
            CategoryManagementServiceFactory cmsFactory = new CategoryManagementServiceFactory();
            _categoryManagementService = cmsFactory.GetCategoryManagementService();

            YPAdmanagementServiceFactory ypFactory = new YPAdmanagementServiceFactory();
            _ypAdmgmtService = ypFactory.GetYPAdmanagementService();
            context.Configuration.ProxyCreationEnabled = false;
        }

        public ActionResult ServiceList(int CategoryId =0, string CategoryName = "", 
            int SubCategoryId=0, string SubCategoryName="", int source = 0, int pagenumber = 1)            
        {
            string currentCurrency = Session["currentCurrency"] != null ? Session["currentCurrency"].ToString() : "Rs. ";
            int currentCountry = Session["currentyCountry"] != null ? Convert.ToInt32(Session["currentCountry"].ToString()) : 101;

            int currentPage = pagenumber;
            int fromRecords = (pagenumber - 1) * 10;
            int toRecords = fromRecords + 10;
            int totalRecords = 0;

            List<USPGetYPAdsByCountryResponse> finalResult =  new List<USPGetYPAdsByCountryResponse>();

            if (SubCategoryId > 0)
            {
               totalRecords =  context.Usp_GetYPAdsBySubCategory(SubCategoryId).ToList().Count();
                List<Usp_GetYPAdsBySubCategory_Result> tempList = context.Usp_GetYPAdsBySubCategory(SubCategoryId).Take(30).ToList();
                CloneObjects.CopyPropertiesTo(tempList, finalResult);
            }
            else
            {
                totalRecords = context.Usp_GetYPAdsByCategory(CategoryId).ToList().Count();
                List<Usp_GetYPAdsByCategory_Result> tempList = new List<Usp_GetYPAdsByCategory_Result>();
                tempList = context.Usp_GetYPAdsByCategory(CategoryId).Take(30).ToList();
                CloneObjects.CopyPropertiesTo(tempList, finalResult);
            }
            
            

            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            else
            {
                catDropsHome = new CommonController().GetHomeDropdowns();
                Session["CatDrop"] = catDropsHome;
            }
            ViewBag.CatsDrop = catDropsHome;
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            else
            {
                serviceDrop = new CommonController().GetServiceCategories();
                Session["ServiceDrop"] = serviceDrop;
            }
            ViewBag.ServiceDrop = serviceDrop;

            List<ServiceSubCategory> SubCats = new List<ServiceSubCategory>();
            SubCategoryListRequest slrs = new SubCategoryListRequest();
            slrs.CategoryId = CategoryId;
            var apiResponse = _categoryManagementService.GetServicesSubCategories(slrs);
            SubCats = apiResponse.Response;

            ViewBag.SubCats = SubCats;
            ViewBag.CategoryId = CategoryId;
            ViewBag.CategoryName = CategoryName;
            ViewBag.SubCategoryName = SubCategoryName;
            ViewBag.SubCategoryId = SubCategoryId;
            ViewBag.currentCurrency = currentCurrency;
            ViewBag.TotalRecords = totalRecords;
            ViewBag.CurrentPageNumber = pagenumber;
            return View(finalResult);
        }

        public ActionResult ServiceDetail(int Id = 0)
        {
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            else
            {
                catDropsHome = new CommonController().GetHomeDropdowns();
                Session["CatDrop"] = catDropsHome;
            }
            ViewBag.CatsDrop = catDropsHome;
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            else
            {
                serviceDrop = new CommonController().GetServiceCategories();
                Session["ServiceDrop"] = serviceDrop;
            }
            ViewBag.ServiceDrop = serviceDrop;

            return View();
        }

        public ActionResult PostService()
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;
            int currentUserId = Session["currentUserId"] != null ? Convert.ToInt32(Session["currentUserId"]) : 0;
            if (currentUserId == 0)
            {
                return RedirectToAction("Login", "Authenticate", new { returnUrl = "/Services/PostService" });
            }

            return View();
        }

        [UserAuthenticationFilter]
        [HttpGet]
        public ActionResult FinalPost(int CategoryIdPost = 0, int SubCategoryIdPost=0, 
            string SelectedSubCategoryName="", string SelectedCategoryName = "")
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;


            List<USPGetOpeningDaysResponse> openingDays = new List<USPGetOpeningDaysResponse>();
            var odResponse = _categoryManagementService.GetOpeningDays();
            List<USPAddTypesReponse> adTypes = new List<USPAddTypesReponse>();
            var adResponse = _categoryManagementService.GetAddTypes();


            adTypes = adResponse.Response;
            openingDays = odResponse.Response;

            int selectedAdTypeId = 0;
            int selectedOpeningDayId = 0;
            ViewBag.OpeningDayId = new SelectList(openingDays, "OpeningId", "DayTime", selectedOpeningDayId.ToString());
            ViewBag.AddTypeId = new SelectList(adTypes, "AddTypeId", "AddTypeName", selectedAdTypeId.ToString());
            ViewBag.SubcategoryName = SelectedSubCategoryName;
            ViewBag.SelectedSubCategoryName = SelectedSubCategoryName;
            ViewBag.SelectedCategoryName = SelectedCategoryName;
            ViewBag.SubcategoryId = SubCategoryIdPost;
            ViewBag.CategoryId = CategoryIdPost;
            ViewBag.CategoryName = SelectedCategoryName; 
            ViewBag.CountryIdSelected = 0;
            ViewBag.StateIdSelected = 0;
            ViewBag.CityIdSelected = 0;

            List<USPGetCountriesListResponse> Countries = new List<USPGetCountriesListResponse>();
            Countries = _categoryManagementService.GetCountries();
            ViewBag.CountryId = new SelectList(Countries,"CountryId","CountryName","0");




            return View();
        }

        [UserAuthenticationFilter]
        [HttpPost]
        public ActionResult FinalPost(YPServicePostRequest ypr)
        {
            if (!string.IsNullOrEmpty(ypr.OtherCity))
            {
                ModelState.Remove("CityId");
            }
            if (ModelState.IsValid)
            {
                bool res = SavePost(ypr);
                return RedirectToAction("PostSuccess");
            }
            else
            {
                List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
                List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
                if (Session["CatDrop"] != null)
                {
                    catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
                }
                if (Session["ServiceDrop"] != null)
                {
                    serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
                }
                ViewBag.CatsDrop = catDropsHome;  
                ViewBag.ServiceDrop = serviceDrop;

EcommerceWEBApplication/Views/Services/PostService.cshtml
@{
    ViewBag.Title = "PostService";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}

<script>
    $(document).ready(function () {
        $('#ServiceForm').submit(function (e) {
            var catid = $("#CategoryIdPost").val();
            var subcatid = $("#SubCategoryIdPost").val();
            if (!(catid > 0) || !(subcatid > 0)) {
                $('#notSelectederror').html('Select Category and Subcategory to move forward');
                e.preventDefault();
            }
            
        });

    });
    function GetSubCats(id,name)
    {
        $('#SelectedCategory').html(name);
        $("#CategoryIdPost").val(id);
        $("#SelectedCategoryName").val(name);
        var url = '/Services/GetSucategories';
        $.get(url, { id: id })
            .done(function (response) {
                $('#SubCategoryResult').html(response);
            });
    }
</script>
<section id="main" class="clearfix ad-post-page">
    <div class="container">

        <div class="breadcrumb-section">
            <!-- breadcrumb -->
            <ol class="breadcrumb">
                <li><a href="index.html">Home</a></li>
                <li>Ad Post</li>
            </ol><!-- breadcrumb -->
            <h2 class="title">Post Free Ad</h2>
        </div><!-- banner -->



        <div id="ad-post">
            @using (Html.BeginForm("FinalPost", "Services", FormMethod.Get, new { @id="ServiceForm"}))
            {
                <div class="row category-tab">
                    <div class="col-lg-4 col-md-6">
                        <div class="section cat-option select-category post-option">
                            <h4>Select a Category</h4>
                            <ul role="tablist" class="nav nav-tabs">
                                @foreach (var cat in ViewBag.ServiceDrop)
                                {
                                    <li>
                                        <a href="#" aria-controls="cat1" role="tab" data-toggle="tab" onclick="GetSubCats(@cat.CategoryId,'@cat.CategoryName')">
                                            @*<span class="select">
                                            <img src="~/Resources/images/icon/@cat.CategoryImage" alt="Images" class="img-">
                                        </span>*@
                                            @cat.CategoryName
                                        </a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>

                    <!-- Tab panes -->
                    <div class="col-lg-4 col-md-6">
                        <div class="section tab-content subcategory post-option">
                            <h4>Select a Subcategory</h4>
                            @*<div role="tabpanel" class="tab-pane active show" id="cat1">*@
                            <div id="SubCategoryResult">

                                @*</div>*@
                            </div>
                           
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="section next-stap post-option">
                            <h2>You have selcted</h2>
                            <p>Category -> <span id="SelectedCategory" style="color:darkblue;" name="SelectedCategory"></span></p>
                            <p>Sub Category -> <span id="SelectedSubCategory" name="SelectedSubCategory"></span></p>
                            <div class="btn-section">
                                <input type="hidden" name="CategoryIdPost" id="CategoryIdPost" />
                                <input type="hidden" name="SelectedCategoryName" id="SelectedCategoryName" />
                                <input type="hidden" name="SelectedSubCategoryName" id="SelectedSubCategoryName" />
                                <input type="hidden" name="SubCategoryIdPost" id="SubCategoryIdPost" />
                                <button type="submit" class="btn btn-success">Next</button>
                                
                                <a href="~/Home/Index" class="btn-info">or Cancel</a>
                                <span class="text-danger" id="notSelectederror"></span>
                            </div>
                        </div>
                    </div><!-- next-stap -->
                </div>
            }

            <div class="row">
                <div class="col-sm-8 offset-sm-2 text-center">
                    <div class="ad-section">
                        <a href="#"><img src="~/Resources/images/ads/3.jpg" alt="Image" class="img-fluid"></a>
                    </div>
                </div>
            </div><!-- row -->
        </div>
    </div><!-- container -->
</section><!-- post-page -->

EcommerceWEBApplication/Views/Services/PostSuccess.cshtml
@{
    ViewBag.Title = "PostSuccess";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<section id="main" class="clearfix published-page">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <div class="congratulations">
                    <i class="fa fa-check-square-o"></i>
                    <h2>Congratulations!</h2>
                    <h4>Your service is successfully posted.</h4>
                    <h3>
                        Our team will priview the Posted serivce and approve it shortly.
                    </h3>
                    <h4 style="color:blueviolet"> </h4>
                    <a href="~/Home/Index" class="btn btn-success">Back to Home</a>
                    <a class="btn btn-warning" href="~/PostProduct/SelectType">Post another </a>
                </div>
            </div>
        </div><!-- row -->
    </div><!-- container -->
</section><!-- main -->

EcommerceWEBApplication/Views/Services/_SubcatsViewPost.cshtml
@model IEnumerable<Components.ResponseObjects.ServiceSubCategory>

  
    <ul>
        @foreach (var v in Model)
        {
       
            <li><a href="#" onclick="SelectedData(@v.SubCategoryId,'@v.SubCategoryName')">@v.SubCategoryName</a></li>
       
            

        }
    </ul>

<script>
    function SelectedData(id,Name) {
        $('#SelectedSubCategory').html(Name);
        $("#SubCategoryIdPost").val(id);
        $("#SelectedSubCategoryName").val(Name); 
    }
</script>