EcommerceWEBApplication/Controllers/AuthenticateController.cs
using BAL.Factory;
using BAL.Interfaces;
using Components.RequestObjects;
using Components.ResponseObjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcommerceWEBApplication.Controllers
{
    public class AuthenticateController : Controller
    {
        private readonly IUserManagentService _userManagementService;
        private readonly ICategoryManagementService _categoryManagementService;
        public AuthenticateController()
        {
            UserManagentServiceFactory usFactory = new UserManagentServiceFactory();
            _userManagementService = usFactory.GetUserManagmentService();
            CategoryManagementServiceFactory catFactory = new CategoryManagementServiceFactory();
            _categoryManagementService = catFactory.GetCategoryManagementService();
        }

        public ActionResult Login(string returnUrl="")
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;

            ViewBag.ErrorMessage = "";
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginRequest request)
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;

            LoginResponse result = new LoginResponse();

            

            if (ModelState.IsValid)
            {
                try
                {
                    var apiResponse = _userManagementService.LoginCheck(request);
                    if (apiResponse.Succeded)
                    {
                        result = apiResponse.Response;
                        if (result.SuccessCode == 1)
                        {
                        
                            Session["currentUserId"] = result.Id;
                            Session["CurrentUserName"] = result.Username;
                            Session["CustomerType"] = result.CustomerType;
                            if (!string.IsNullOrEmpty(request.returnUrl))
                            {
                                return Redirect(request.returnUrl);
                            }
                            else {
                                return Redirect("/Home/Index");
                            }
                            
                        }
                        else
                        {
                            ViewBag.ErrorMessage = result.Message;
                            return View(request);
                        }
                    }
                    else {
                        //send error message to view;
                        ViewBag.ErrorMessage = "Unable to login now, please try again";
                        return View(request);
                    }

                }
                catch (Exception ex)
                {

                }
            }
            ViewBag.ErrorMessage = "";
            return View(request);

        }

        public ActionResult Register()
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;
            ViewBag.ErrorMessage = "";
            List<USPGetCountriesListResponse> Countries = new List<USPGetCountriesListResponse>();
            Countries = _categoryManagementService.GetCountries();
            ViewBag.CountryId= Countries;
            return View();
        }


        [HttpPost]
        public ActionResult Register(CustomerSaveRequest request)
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;
            ViewBag.ErrorMessage = "";
            List<USPGetCountriesListResponse> Countries = new List<USPGetCountriesListResponse>();
            Countries = _categoryManagementService.GetCountries();
            ViewBag.CountryId = Countries;
            
            int? CountryIdSelected = 0;
            int? StateIdSelected = 0;
            string CityIdSelected = string.Empty;
            if (request.CountryId > 0) CountryIdSelected = request.CountryId;
            if (request.StateProvinceId > 0) StateIdSelected = request.StateProvinceId;
            if (!string.IsNullOrEmpty(request.City)) CityIdSelected = request.City;

            if (ModelState.IsValid)
            {
                
                //check for emailavalable
                ProcessResponse ps = new ProcessResponse();
                LoginRequest lr = new LoginRequest();
                lr.emailId = request.Email;
                ps = _userManagementService.EmailAvailableCheck(lr);
                if (ps.StatusCode == 0)
                {
                    ModelState.AddModelError("Email", "Emailid not avaialble");
                }
            }
            if (ModelState.IsValid)
            {

                ProcessResponse pr = new ProcessResponse();
                pr = _userManagementService.RegisterUser(request);
                if (pr.CurrentId > 0)
                {
                    return RedirectToAction("RegistrationSuccess", new { UserType = request.CustomerType, Id = pr.CurrentId });
                }
                else
                {
                    ViewBag.ErrorMessage = "Unable to register now, please try later : " + pr.Message;
                    return View(request);
                }



                
            }



            return View(request);
        }


        public ActionResult RegistrationSuccess(string UserType, int Id)
        {
            List<ServiceCategoriesResponse> serviceDrop = new List<ServiceCategoriesResponse>();
            List<CategoryDropHomeResponse> catDropsHome = new List<CategoryDropHomeResponse>();
            if (Session["CatDrop"] != null)
            {
                catDropsHome = (List<CategoryDropHomeResponse>)Session["CatDrop"];
            }
            if (Session["ServiceDrop"] != null)
            {
                serviceDrop = (List<ServiceCategoriesResponse>)Session["ServiceDrop"];
            }
            ViewBag.CatsDrop = catDropsHome;
            ViewBag.ServiceDrop = serviceDrop;

            List<USPGetCountriesListResponse> Countries = new List<USPGetCountriesListResponse>();
            Countries = _categoryManagementService.GetCountries();
            ViewBag.CountryId = Countries;
            return View();
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
    
    }
}

EcommerceWEBApplication/Views/Authenticate/Login.cshtml
@model Components.RequestObjects.LoginRequest
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}


<section id="main" class="clearfix user-page">
    <div class="container">
        <div class="row text-center">
            <!-- user-login -->
            <div class="col-md-8 offset-md-2 col-lg-6 offset-lg-3">
                <div class="user-account">
                    <h2>User Login</h2>
                    <!-- form -->
                    @using (Html.BeginForm("Login", "Authenticate", FormMethod.Post))
                    {
                        <div class="form-group">
                            <input type="text" class="form-control" name="emailId" placeholder="Username">
                            @Html.ValidationMessageFor(b => b.emailId, null, new { @class = "text-danger"})
                        </div>
                        <div class="form-group">
                            <input type="password" name="pword" class="form-control" placeholder="Password">
                            @Html.ValidationMessageFor(b => b.pword, null, new { @class = "text-danger" })
                        </div>
                        <button type="submit" class="btn">Login</button>
                        <input type="hidden" value="@ViewBag.returnUrl" id="returnUrl" name="returnUrl"/>
                        <br />
                        <sapn class="text-danger">@ViewBag.ErrorMessage</sapn>

                    }



                    <!-- form -->
                    <!-- forgot-password -->
                    <div class="user-option">
                       
                        <div class="pull-right forgot-password">
                            <a href="#">Forgot password</a>
                        </div>
                    </div><!-- forgot-password -->
                </div>
                <a href="~/Authenticate/Registration" class="btn-primary">Create a New Account</a>
            </div><!-- user-login -->
        </div><!-- row -->
    </div><!-- container -->
</section><!-- signin-page -->

EcommerceWEBApplication/Views/Authenticate/Register.cshtml
@model Components.RequestObjects.CustomerSaveRequest
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<script>
    $(document).ready(function () {
        var countryHome = $('#CoutryIdSelected').val();
        if (countryHome > 0) {
            $('#CountryId').val(countryHome);
        }
        var stateData = $('#StateIdSelected').val();
        if (stateData > 0) {
            $('#StateiId').val(stateData);
        }
        GetStates();
    });
    $("input[type=checkbox]").change(function () {
        if ($(this).prop("checked")) {
            $(this).val(true);
        } else {
            $(this).val(false);
        }
    });

    function GetStates() {
        var countryId = $('#CountryId option:selected').val();
        var stateData = $('#StateIdSelected').val();
        $.ajax({
            url: '/Common/GetStatesByCountry?id=' + countryId,
            data: {},
            type: 'post',
            success: function (result) {
                var res = result.res;
                $('#StateId').empty();
                for (var i = 0; i < res.length; i++) {
                    if (stateData > 0 && stateData == res[i].StateId) {
                        $('#StateId').append('<option value="' + res[i].StateId + '" selected>' + res[i].StateName + '</option>');
                    }
                    else {
                        $('#StateId').append('<option value="' + res[i].StateId + '">' + res[i].StateName + '</option>');
                    }

                }
                GetCities();


            }
        });
    }

    function GetCities() {
        var stateid = $('#StateId option:selected').val();
        var cityHome = $('#CityIdSelected').val();

        $.ajax({
            url: '/Common/GetCitiesByState?id=' + stateid,
            data: {},
            type: 'post',
            success: function (result) {
                var res = result.res;
                $('#CityId').empty();
                for (var i = 0; i < res.length; i++) {
                    if (cityHome > 0 && res[i].CityName == cityHome) {
                        $('#CityId').append('<option value="' + res[i].CityName + '" selected>' + res[i].CityName + '</option>');
                    }
                    else {
                        $('#CityId').append('<option value="' + res[i].CityName + '">' + res[i].CityName + '</option>');
                    }


                }

            }
        });
    }
</script>
<section id="main" class="clearfix user-page">
    <div class="container">
        <div class="row text-center">
            <!-- user-login -->
            <div class="col-md-12 col-lg-12">
                <div class="user-account">
                    <h2>Create a MyQShop Account</h2>
                    @using (Html.BeginForm("Register", "Authenticate", FormMethod.Post))
                    {
                        <div class="col-lg-12 col-md-12">
                            <div class="row">


                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">
                                        First Name
                                    </label>
                                    @Html.TextBoxFor(m => m.FirstName, new { @class = "form-control", @placeholder = "Fist Name" })
                                    @Html.ValidationMessageFor(m => m.FirstName, null, new { @class = "text-danger" })

                                </div>
                                <div class="form-group col-lg-3">
                                    <label style="text-align:left;"> Last Name</label>
                                    @Html.TextBoxFor(m => m.LastName, new { @class = "form-control", @placeholder = "Last Name" })
                                    @Html.ValidationMessageFor(m => m.LastName, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-md-3">
                                    <label style="text-align:left;"> Email</label>
                                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control", @placeholder = "Email id" })
                                    @Html.ValidationMessageFor(m => m.Email, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-md-3">
                                    <label style="text-align:left;"> Contact Number</label>
                                    @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control", @placeholder = "Contact Number" })
                                    @Html.ValidationMessageFor(m => m.PhoneNumber, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <div class="row">


                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">
                                        Password
                                    </label>
                                    @Html.PasswordFor(m => m.password, new { @class = "form-control", @placeholder = "Password" })
                                    @Html.ValidationMessageFor(m => m.password, null, new { @class = "text-danger" })

                                </div>
                                <div class="form-group col-lg-3">
                                    <label style="text-align:left;"> Confirm Password</label>
                                    @Html.PasswordFor(m => m.cnfpassword, new { @class = "form-control", @placeholder = "Confirm Password" })
                                    @Html.ValidationMessageFor(m => m.cnfpassword, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">Country</label>
                                    <select class="form-control" name="CountryId" id="CountryId" onchange="GetStates()">
                                        @foreach (var v in ViewBag.CountryId)
                                        {
                                            <option value="@v.CountryId">@v.CountryName</option>
                                        }
                                    </select>
                                    @Html.ValidationMessageFor(m => m.CountryId, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">State</label>
                                    <select id="StateId" name="StateProviceId" class="form-control" onchange="GetCities()" onclick="GetCities()">
                                        <option value="null">-- Select State --</option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.StateProvinceId, null, new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-12 col-md-12">
                            <div class="row">
                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">City</label>
                                    <select class="form-control" name="City" id="CityId">
                                        <option value=""></option>
                                    </select>
                                    @Html.ValidationMessageFor(m => m.City, null, new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">
                                        H.No/Street
                                    </label>
                                    @Html.TextBoxFor(m => m.Address1, new { @class = "form-control", @placeholder = "H.No/Street" })
                                    @Html.ValidationMessageFor(m => m.Address1, null, new { @class = "text-danger" })

                                </div>
                                <div class="form-group col-lg-3">
                                    <label style="text-align:left;">Location/Locality/County</label>
                                    @Html.TextBoxFor(m => m.Address2, new { @class = "form-control", @placeholder = "Location/Locality/County" })
                                    @Html.ValidationMessageFor(m => m.Address2, null, new { @class = "text-danger" })
                                </div>
                                <div class="form-group col-lg-3">
                                    <label style="text-align:left;">Postal Code</label>
                                    @Html.TextBoxFor(m => m.ZipPostalCode, new { @class = "form-control", @placeholder = "Postal zip code" })
                                    @Html.ValidationMessageFor(m => m.ZipPostalCode, null, new { @class = "text-danger" })
                                </div>

                                <div class="form-group col-md-3">
                                    <label style="text-align:left;">Registraton Type</label>
                                    <select id="CustomerType" name="CustomerType" class="form-control">
                                        <option value="Customer">Customer</option>
                                        <option value="Vendor">Vendor</option>
                                        <option value="Marketing">Marketing</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                       

                      



                        <div class="checkbox">
                            <label class="pull-left checked" for="signing"><input type="checkbox" name="signing" id="signing"> By signing up for an account you agree to our Terms and Conditions </label>
                        </div><!-- checkbox -->
                        <input type="hidden" id ="CountryIdSelected" name="CountryIdSelected" value="@ViewBag.CountryIdSelected" />
                        <input type="hidden" id="CityIdSelected" name="CityIdSelected" value="@ViewBag.CityIdSelected" />
                        <input type="hidden" id="StateIdSelected" name="StateIdSelected" value="@ViewBag.StateIdSelected" />
                        <button type="submit"  class="btn">Save</button>
                        <span class="text-danger">@ViewBag.ErrorMessage</span>

                    }

                    <!-- checkbox -->

                </div>
                    </div><!-- user-login -->
        </div><!-- row -->
    </div><!-- container -->
</section><!-- signup-page -->

EcommerceWEBApplication/Views/Authenticate/RegistrationSuccess.cshtml
@{
    ViewBag.Title = "RegistrationSuccess";
    Layout = "~/Views/Shared/_MasterLayout.cshtml";
}
<section id="main" class="clearfix published-page">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <div class="congratulations">
                    <i class="fa fa-check-square-o"></i>
                    <h2>Congratulations!</h2>
                    <h4>Your registration is successful.</h4>
                    <h3>If you are registered as Customer, start browsing MyQShops.
                                </h3> 
                    <h4 style="color:blueviolet">  If your a Vendor/Sales our admin will contact you soon.</h4>
                    <a href="~/Home/Index" class="btn btn-success">Back to Home</a>
                    <a class="btn btn-warning" href="~/Authenticate/Login">Login (if you are Customer)</a>
                </div>
            </div>
        </div><!-- row -->
    </div><!-- container -->
</section><!-- main -->